### ISSUE TITLE
프로젝트 CD 구현 

### ISSUE THREAD

**Issue by Jane096** [f-lab-edu/event-recommender-festa#113]

**Comment by Jane096** [comment]
![image](https://user-images.githubusercontent.com/58355531/111495904-279d0700-8783-11eb-801a-31548e606592.png)


@f-lab-dev @Yo0oN  로그를 확인해봤을 때 배포가 잘 진행된 것 같습니다! 

그리고 지금은 `develop` 브랜치를 기준으로 빌드해서 배포 중인데 git-flow 에서는 `release` 브랜치에서 한다고 봤었습니다.
`develop` 이 아닌 `release` 로 바꿔야할까요?

**Comment by Yo0oN** [comment]
아직 release브랜치가 없기때문에 일단 develop으로 하고 이후 개발 완료시 브랜치를 변경하는건 어떨까요?

**Comment by Jane096** [comment]
네네!! 그럼 지금 남아있는 이슈 모두 작업완료된 이후에 진행하기로 해요~!
