### ISSUE TITLE
MemberDAO 파라미터 수정

### ISSUE THREAD

**Issue by Yo0oN** [f-lab-edu/event-recommender-festa#140]
MyBatis 문서를 보던 중 파라미터를 넘길 때 xml에서 설정해둔 타입과 일치하지 않더라도 ParameterHandler에 의해 자동으로 맵핑된다는 글을 보았습니다.
그런데 값이 여러개 넘어갈 경우 객체나 Map을 이용하지 않고 넘기면 넘어간 변수명과 쿼리에서 사용하는 이름이 같더라도 값이 넘어간 순서대로 맵핑되어서 값을 넘길 때 `@Param` 어노테이션을 이용하여 파라미터의 이름을 지정해주어야한다고 합니다. 이전에 작성한 메소드 중 DTO를 이용하지 않은 메소드들과, 맵핑되는 쿼리문의 parameterType을 수정하기 위해 이슈를 열었습니다..!

**Comment by Jane096** [comment]
아!!! 그래서 순서를 안지키면 이상하게 제대로 동작을 안하던게 있던거였군요 ㅠㅠ 문서를 다시 읽어봐야겠습니다 ㅠ
